name: Ogenblick
options:
 
  bundleIdPrefix: com.marksimmons.ogenblick
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  Ogenblick:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Ogenblick
    resources:
      - Ogenblick/Resources
    settings:
      base:
        INFOPLIST_FILE: Ogenblick/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.marksimmons.ogenblick.app
        TARGETED_DEVICE_FAMILY: 1
    entitlements:
      path: Ogenblick/Ogenblick.entitlements
    scheme:
      gatherCoverageData: false


